// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/internal/dao/internal"
)

// internalMigrationsDao is internal type for wrapping internal DAO implements.
type internalMigrationsDao = *internal.MigrationsDao

// migrationsDao is the data access object for table migrations.
// You can define custom methods on it to extend its functionality as you wish.
type migrationsDao struct {
	internalMigrationsDao
}

var (
	// Migrations is globally public accessible object for table migrations operations.
	Migrations = migrationsDao{
		internal.NewMigrationsDao(),
	}
)

// Fill with you ideas below.
